import type { GridFilterOperator } from '../core';

const zh: Record<string, string> = {
  contains: '包含',
  notContains: '不包含',
  equals: '等于',
  notEquals: '不等于',
  startsWith: '开头是',
  endsWith: '结尾是',
  greaterThan: '大于',
  greaterThanOrEqual: '大于等于',
  lessThan: '小于',
  lessThanOrEqual: '小于等于',
  between: '介于',
  notBetween: '不介于',
  in: '属于任意一个',
  notIn: '不属于任意一个',
  containsAny: '包含任意一个',
  containsAll: '包含全部',
  containsNone: '全部不包含',
  before: '早于',
  after: '晚于',
  onOrBefore: '不晚于',
  onOrAfter: '不早于',
  today: '今天',
  yesterday: '昨天',
  tomorrow: '明天',
  thisWeek: '本周',
  lastWeek: '上周',
  thisMonth: '本月',
  lastMonth: '上月',
  last7Days: '最近 7 天',
  last30Days: '最近 30 天',
  isTrue: '是',
  isFalse: '否',
  isEmpty: '为空',
  isNotEmpty: '不为空',
};

const en: Record<string, string> = {
  contains: 'Contains',
  notContains: 'Does not contain',
  equals: 'Equals',
  notEquals: 'Does not equal',
  startsWith: 'Starts with',
  endsWith: 'Ends with',
  greaterThan: 'Greater than',
  greaterThanOrEqual: 'Greater than or equal',
  lessThan: 'Less than',
  lessThanOrEqual: 'Less than or equal',
  between: 'Between',
  notBetween: 'Not between',
  in: 'Is any of',
  notIn: 'Is not any of',
  containsAny: 'Contains any',
  containsAll: 'Contains all',
  containsNone: 'Contains none',
  before: 'Before',
  after: 'After',
  onOrBefore: 'On or before',
  onOrAfter: 'On or after',
  today: 'Today',
  yesterday: 'Yesterday',
  tomorrow: 'Tomorrow',
  thisWeek: 'This week',
  lastWeek: 'Last week',
  thisMonth: 'This month',
  lastMonth: 'Last month',
  last7Days: 'Last 7 days',
  last30Days: 'Last 30 days',
  isTrue: 'True',
  isFalse: 'False',
  isEmpty: 'Is empty',
  isNotEmpty: 'Is not empty',
};

export function operatorLabel(operator: GridFilterOperator, language?: string): string {
  const labels = language?.toLocaleLowerCase().startsWith('en') ? en : zh;
  return labels[operator] || operator;
}

export const noValueOperators = new Set<GridFilterOperator>([
  'isTrue',
  'isFalse',
  'isEmpty',
  'isNotEmpty',
  'today',
  'yesterday',
  'tomorrow',
  'thisWeek',
  'lastWeek',
  'thisMonth',
  'lastMonth',
  'last7Days',
  'last30Days',
]);
